<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQ0LHz5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQ0LHz5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQ0LHz5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQ0LHz5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPQ0LHz5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PQ0LHz5',
    'container.build_id' => 'ab5b59fc',
    'container.build_time' => 1621728971,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQ0LHz5');
