<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'blog' => [[], ['_controller' => 'App\\Controller\\BlogController::index'], [], [['text', '/']], [], []],
    'blogshow' => [['id'], ['_controller' => 'App\\Controller\\BlogController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/blog']], [], []],
    'user_posts' => [[], ['_controller' => 'App\\Controller\\BlogController::renderUserPosts'], [], [['text', '/posts/user']], [], []],
    'addpost' => [[], ['_controller' => 'App\\Controller\\BlogController::addpost'], [], [['text', '/addpost']], [], []],
    'display_posts' => [[], ['_controller' => 'App\\Controller\\BlogController::desplayposts'], [], [['text', '/displayposts']], [], []],
    'delete_post' => [[], ['_controller' => 'App\\Controller\\BlogController::deletePost'], [], [['text', '/deletePost']], [], []],
    'detailspost' => [[], ['_controller' => 'App\\Controller\\BlogController::details'], [], [['text', '/detailspost']], [], []],
    'display_comments' => [[], ['_controller' => 'App\\Controller\\BlogController::desplaycomments'], [], [['text', '/displaycomments']], [], []],
    'addcomment' => [[], ['_controller' => 'App\\Controller\\BlogController::addcomment'], [], [['text', '/addcomment']], [], []],
    'delete_comment' => [[], ['_controller' => 'App\\Controller\\BlogController::deletecomment'], [], [['text', '/deletecomment']], [], []],
    'comment_add' => [[], ['_controller' => 'App\\Controller\\CommentsController::add'], [], [['text', '/comment/add']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\BlogController:index'], [], [['text', '/']], [], []],
];
